### ISSUE TITLE
NullPointerException decompiling org/eclipse/jetty/util/MultiException

### ISSUE THREAD

**Issue by mr-jolly** [mstrobel/procyon#28]
Decompiling org/eclipse/jetty/util/MultiException...
java.lang.NullPointerException
        at com.strobel.decompiler.languages.java.ast.transforms.RewriteSwitchExpressionsTransform.visitSwitchStatement(RewriteSwitchExpressionsTransform.java:238)
        at com.strobel.decompiler.languages.java.ast.transforms.RewriteSwitchExpressionsTransform.visitSwitchStatement(RewriteSwitchExpressionsTransform.java:26)
        at com.strobel.decompiler.languages.java.ast.SwitchStatement.acceptVisitor(SwitchStatement.java:66)
        at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitChildren(DepthFirstAstVisitor.java:41)
        at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitBlockStatement(DepthFirstAstVisitor.java:104)
        at com.strobel.decompiler.languages.java.ast.BlockStatement.acceptVisitor(BlockStatement.java:72)
        at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitChildren(DepthFirstAstVisitor.java:41)
        at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitMethodDeclaration(DepthFirstAstVisitor.java:229)
        at com.strobel.decompiler.languages.java.ast.ContextTrackingVisitor.visitMethodDeclarationOverride(ContextTrackingVisitor.java:81)
        at com.strobel.decompiler.languages.java.ast.ContextTrackingVisitor.visitMethodDeclaration(ContextTrackingVisitor.java:73)
        at com.strobel.decompiler.languages.java.ast.ContextTrackingVisitor.visitMethodDeclaration(ContextTrackingVisitor.java:28)
        at com.strobel.decompiler.languages.java.ast.MethodDeclaration.acceptVisitor(MethodDeclaration.java:94)
        at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitChildren(DepthFirstAstVisitor.java:41)
        at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitTypeDeclaration(DepthFirstAstVisitor.java:259)
        at com.strobel.decompiler.languages.java.ast.ContextTrackingVisitor.visitTypeDeclarationOverride(ContextTrackingVisitor.java:66)
        at com.strobel.decompiler.languages.java.ast.ContextTrackingVisitor.visitTypeDeclaration(ContextTrackingVisitor.java:57)
        at com.strobel.decompiler.languages.java.ast.ContextTrackingVisitor.visitTypeDeclaration(ContextTrackingVisitor.java:28)
        at com.strobel.decompiler.languages.java.ast.TypeDeclaration.acceptVisitor(TypeDeclaration.java:90)
        at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitChildren(DepthFirstAstVisitor.java:41)
        at com.strobel.decompiler.languages.java.ast.DepthFirstAstVisitor.visitCompilationUnit(DepthFirstAstVisitor.java:269)
        at com.strobel.decompiler.languages.java.ast.CompilationUnit.acceptVisitor(CompilationUnit.java:82)
        at com.strobel.decompiler.languages.java.ast.ContextTrackingVisitor.run(ContextTrackingVisitor.java:97)
        at com.strobel.decompiler.languages.java.ast.transforms.RewriteSwitchExpressionsTransform.run(RewriteSwitchExpressionsTransform.java:65)
        at com.strobel.decompiler.languages.java.ast.transforms.TransformationPipeline.runTransformationsUntil(TransformationPipeline.java:98)
        at com.strobel.decompiler.languages.java.ast.AstBuilder.runTransformations(AstBuilder.java:120)
        at com.strobel.decompiler.languages.java.JavaLanguage.runTransforms(JavaLanguage.java:97)
        at com.strobel.decompiler.languages.java.JavaLanguage.buildAst(JavaLanguage.java:72)
        at com.strobel.decompiler.languages.java.JavaLanguage.decompileType(JavaLanguage.java:59)
        at com.strobel.decompiler.DecompilerDriver.decompileType(DecompilerDriver.java:333)
        at com.strobel.decompiler.DecompilerDriver.decompileJar(DecompilerDriver.java:254)
        at com.strobel.decompiler.DecompilerDriver.main(DecompilerDriver.java:129)
[jetty-util-9.4.33.v20201020.jar.zip](https://github.com/mstrobel/procyon/files/7138855/jetty-util-9.4.33.v20201020.jar.zip)

**Comment by mstrobel** [comment]
This appears to be fixed for the next release (branch `post-java8-features`).
