### ISSUE TITLE
Can't decompile anymore - IllegalStateException

### ISSUE THREAD

**Issue by hanneshorn** [mstrobel/procyon#36]
As the title line says!

Using: Java SE 8u311

java.lang.IllegalStateException: Invalid BootstrapMethods attribute entry: 2 additional arguments required for method java/lang/invoke/StringConcatFactory.makeConcatWithConstants, but only 1 specified.

**Comment by hanneshorn** [comment]
Here's an example trace:
        at com.strobel.assembler.ir.Error.invalidBootstrapMethodEntry(Error.java:243)
        at com.strobel.assembler.ir.MetadataReader.readAttributeCore(MetadataReader.java:254)
        at com.strobel.assembler.metadata.ClassFileReader.readAttributeCore(ClassFileReader.java:261)
        at com.strobel.assembler.ir.MetadataReader.inflateAttributes(MetadataReader.java:411)
        at com.strobel.assembler.metadata.ClassFileReader.visitAttributes(ClassFileReader.java:1135)
        at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:439)
        at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:366)
        at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:124)
        at com.strobel.decompiler.NoRetryMetadataSystem.resolveType(DecompilerDriver.java:463)
        at com.strobel.assembler.metadata.MetadataSystem.lookupTypeCore(MetadataSystem.java:81)
        at com.strobel.assembler.metadata.MetadataResolver.lookupType(MetadataResolver.java:46)
        at com.strobel.decompiler.DecompilerDriver.decompileType(DecompilerDriver.java:276)
        at com.strobel.decompiler.DecompilerDriver.decompileJar(DecompilerDriver.java:238)

**Comment by mstrobel** [comment]
This is fixed for the next release (branch `post-java8-features`).
